In [ ]:
#importing all necessary libraries 
import pandas as pd
import numpy as np
import sklearn
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder


In [ ]:
df = pd.read_csv('/content/mushroom edibility classification dataset.csv')
df.head(10)


Unnamed: 0      class  cap-shape  ...  spore-print-color  population habitat
0           0  poisonous        5.0  ...                  2           3       5
1           1     edible        5.0  ...                  3           2       1
2           2     edible        0.0  ...                  3           2       3
3           3  poisonous        5.0  ...                  2           3       5
4           4     edible        5.0  ...                  3           0       1
5           5     edible        5.0  ...                  2           2       1
6           6     edible        0.0  ...                  2           2       3
7           7     edible        0.0  ...                  3           3       3
8           8  poisonous        5.0  ...                  2           4       1
9           9     edible        0.0  ...                  2           3       3

[10 rows x 20 columns]

In [ ]:
df.shape

(3124, 20)

In [ ]:
df.isnull().sum()

Unnamed: 0                  0
class                       0
cap-shape                   8
cap-surface                 0
cap-color                   8
bruises                     0
odor                        0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [ ]:
print("Number of rows with null values in cap-shape column",df["cap-shape"].isnull().sum())
print("Number of rows with null values in cap-color column",df["cap-color"].isnull().sum())

Number of rows with null values in cap-shape column 8
Number of rows with null values in cap-color column 8


In [ ]:
df= df.dropna(axis=0, subset=["cap-shape","cap-color"])
print("Shape after removing null values: ", df.shape)

Shape after removing null values:  (3108, 20)


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3108 entries, 0 to 3123
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                3108 non-null   int64  
 1   class                     3108 non-null   object 
 2   cap-shape                 3108 non-null   float64
 3   cap-surface               3108 non-null   int64  
 4   cap-color                 3108 non-null   float64
 5   bruises                   3108 non-null   object 
 6   odor                      3108 non-null   int64  
 7   stalk-shape               3108 non-null   int64  
 8   stalk-root                3108 non-null   int64  
 9   stalk-surface-above-ring  3108 non-null   int64  
 10  stalk-surface-below-ring  3108 non-null   int64  
 11  stalk-color-above-ring    3108 non-null   int64  
 12  stalk-color-below-ring    3108 non-null   int64  
 13  veil-type                 3108 non-null   int64  
 14  veil-col

In [ ]:
df["class"].unique()

array(['poisonous', 'edible'], dtype=object)

In [ ]:
#Endcoding
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()

df['class'] = enc.fit_transform(df['class'])
df['bruises'] = enc.fit_transform(df['bruises'])
df.head()

Unnamed: 0  class  cap-shape  ...  spore-print-color  population  habitat
0           0      1        5.0  ...                  2           3        5
1           1      0        5.0  ...                  3           2        1
2           2      0        0.0  ...                  3           2        3
3           3      1        5.0  ...                  2           3        5
4           4      0        5.0  ...                  3           0        1

[5 rows x 20 columns]

In [ ]:
from sklearn.model_selection import train_test_split

terget = df["class"].values   
dataset = df.drop(["class"], axis=1).values
x_train, x_test, y_train, y_test = train_test_split(dataset,terget,random_state=42,test_size=0.30) 
print(x_train.shape)
print(x_test.shape)

(2175, 19)
(933, 19)


In [ ]:
print("per-feature minimum before scaling:\n {}".format(x_train.min(axis=0)))
print("per-feature maximum before scaling:\n {}".format(x_train.max(axis=0)))

per-feature minimum before scaling:
 [1. 0. 0. 2. 0. 0. 0. 1. 0. 0. 0. 0. 0. 2. 1. 0. 1. 0. 0.]
per-feature maximum before scaling:
 [3.122e+03 5.000e+00 3.000e+00 9.000e+00 1.000e+00 6.000e+00 1.000e+00
 4.000e+00 2.000e+00 3.000e+00 7.000e+00 7.000e+00 0.000e+00 2.000e+00
 1.000e+00 4.000e+00 6.000e+00 5.000e+00 5.000e+00]


In [ ]:
# Applying MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(x_train)

X_train_scaled = scaler.transform(x_train)
X_test_scaled = scaler.transform(x_test)
print("per-feature minimum after scaling:\n {}".format(
    X_train_scaled.min(axis=0)))
print("per-feature maximum after scaling:\n {}".format(
    X_train_scaled.max(axis=0)))

per-feature minimum after scaling:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
per-feature maximum after scaling:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1.]


In [ ]:
#scatter plot
import matplotlib.pyplot as plt
n=0
plt.scatter (x[x.columns[n]],Y)

In [ ]:
# Applying StandardScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train)

X_train_scaled = scaler.transform(x_train)
X_test_scaled = scaler.transform(x_test)


knn.fit(X_train_scaled, y_train)

# Scaled data Accuracy 
print("Test set score after Applying StandardScaler: {}%".format(round(knn.score(X_test_scaled, y_test)*100,2)))

In [ ]:
#scatter plot
import matplotlib.pyplot as plt
n=0
plt.scatter (X[X.columns[n]],Y)